In [29]:

import numpy as np

sold = np.array( [ [8, 1, 2, 4, 2],
                [6, 1, 2, 3, 2],
                [4, 1, 2, 7, 2]])

print ("quants sold by fruit (row) and day (col):\n" + str(sold) + "\n")

price = np.array([4,2,5])

print ("prices per single fruit: \n" + str(price)+ "\n")

value_per_day = price @ sold
print("value per day: \n"+ str( value_per_day)+ "\n")

day_ones = np.ones(5)
quantity_sold = sold @ day_ones
print("quantity sold per fruit: \n" + str(quantity_sold) + "\n")


day_ones = np.ones(5)
total_value = price @ sold @ day_ones
print("total value: \n" + str(total_value) + "\n")



(sold.T)@(price.T)




quants sold by fruit (row) and day (col):
[[8 1 2 4 2]
 [6 1 2 3 2]
 [4 1 2 7 2]]

prices per single fruit: 
[4 2 5]

value per day: 
[64 11 22 57 22]

quantity sold per fruit: 
[17. 14. 16.]

total value: 
176.0



array([64, 11, 22, 57, 22])